##################################
# BrainGENIE Pipeline 
# Autora: Clara Podaru
###############################

# 1. SETUP
# Cargar librerías
library(data.table)        # Leer matrices grandes
library(writexl)           # Exportar datos en excel
library(ggplot2)           # Visualizaciones

# Establecer directorio de trabajo al del script actual
workingD <- rstudioapi::getActiveDocumentContext()$path
setwd(dirname(workingD))
rm(list = ls())  # limpia el entorno

# 2. CARGAR Y PROCESAR LOS DATOS DE SANGRE
# Entrada de datos: counts_TPM_final (no proporcionado)
# Formato requerido:
  #Columna 1: GeneID (Ensembl ID)
  #Siguientes columnas : muestras
  #Filas: genes
raw_data <- fread("counts_TPM_final.tsv")

#Función para comprobar y transponer los datos si fuese necesario
check_and_transpose_data <- function(raw_data) {
  is_gene_in_rows <- grep("^ENSG", raw_data[[1]])  # Comprueba si la primera columna tiene gene IDs
  if (sum(is_gene_in_rows) > (nrow(raw_data) * 0.9)) {
    gene_names <- raw_data$GeneID
    expr_matrix <- as.matrix(raw_data[, -1, with = FALSE])
    transposed <- t(expr_matrix)  # transpone la matriz
    colnames(transposed) <- gene_names
    sample_ids <- colnames(raw_data)[-1]
    data_df <- data.frame(transposed, check.names = FALSE)
    rownames(data_df) <- sample_ids
    return(data_df)
  } else {
    message("La matriz tiene el formato correcto")
    return(raw_data)
  }
}
data <- check_and_transpose_data(raw_data)  

#3. DEFINIT LA REGIÓN Y LAS CARPETAS DE SALIDA
region <- "Brain_Cerebellum"  # Región cerebral a analizar

#Crear carpeta de output
base_output_dir <- file.path("..", "output_data", "braingenie")
if (!dir.exists(base_output_dir)) dir.create(base_output_dir, recursive = TRUE)

#Subcarpetas organizadas
imputed_dir <- file.path(base_output_dir, "imputed_expression", region)
plot_dir <- file.path(base_output_dir, "plots", region)
summary_stats_dir <- file.path(base_output_dir, "summary_stats")
sig_gene_dir <- file.path(base_output_dir, "significant_genes", region)
models_dir <- file.path(base_output_dir, "models", region)

dirs <- list(imputed_dir, plot_dir, summary_stats_dir, sig_gene_dir, models_dir)
for (d in dirs) if (!dir.exists(d)) dir.create(d, recursive = TRUE)

# 4. CARGAR FUNCIONES Y DATOS DE GTEx

#Archivo externo que contiene las funciones específicas para ejecutar BrainGENIE
source("braingenie_methods.R")  
# Cargar datos de referencia de gtex
path_data <- paste0("normalized_expression_dat_gtexv8/", region, "/")
load_expr_data(path_to_data = path_data)  

# Eliminar las veriones de los ensembl ids
rownames(blood_expr) <- gsub("\\..*", "", rownames(blood_expr))
rownames(brain_expr) <- gsub("\\..*", "", rownames(brain_expr))

# 5. ENTRENAMIENTO DE MODELOS
#Los parámetros escogidos tras realizar el análisis exploratorio: 50 PCs y 10 folds.
# Outputs generated by this step:
# - Trained models: models_dir (organized by brain region)
# - Imputed expression: imputed_dir (organized by brain region)
# - Metrics and plots: summary_stats_dir and plot_dir
# =========================================================
# Run the model for specific PC and fold settings to ensure files exist
retrain_gtex(
  gene_list = colnames(data),
  output = models_dir,
  tissue = region,
  ncomps = 50,
  prop_for_test_set = 0.0,
  n_folds = 10
)

# 6. EVALUAR LOS GENES SIGNIFICATIVOS
perf <- load_cv_performance()  # Cargar las métricas de rendimiento de la validación cruzada 
perf_sig <- perf[perf$Cor >= 0.1 & perf$fdr < 0.05, ]  # Filtrar genes significativos

# Guardar el modelo entrenado con el nombre estandarizado que espera el loop
saveRDS(perf, file = file.path(models_dir, paste0(region, "_BrainGENIE_retrain-50_nfolds10.Rdata")))
#Cada vez que se cambian los parámtros al entrenar el modelos, cambiarlo también en la nomenclatura para guardar el perf

#Define el directorio principal de los genes significativos, organizados por región
sig_gene_dir <- file.path(base_output_dir, "significant_genes", region)

# Crear la carpeta si todavía no existe 
if (!dir.exists(sig_gene_dir)) {
  dir.create(sig_gene_dir, recursive = TRUE)
  cat("Created folder:", sig_gene_dir, "\n")
}
#Definir el nombre del fichero que contiene la region, pcs y folds
filename_sig <- paste0(region, "_significant_genes.tsv")
#Guardar la tabla de genes significativos
write.table(perf_sig,
            file = file.path(sig_gene_dir, filename_sig),
            sep = "\t",
            quote = FALSE,
            row.names = FALSE,
            col.names = TRUE)

cat("Genes significativos almacenados en:", file.path(sig_gene_dir, filename_sig), "\n")

# 7. ANÁLISIS EXPLORATORIO PCs y FOLDS
# Esta sección de código ha sido empleando para analizar las diferentes combinaciones de parámetros
# con el objetivo de encontrar la mejor combinación
# NO ES OBLIGATORIO ejecutar esta parte para que braingenie funcione

PCs <- c(10,20, 40, 50, 60)  
folds <- c(5, 10, 20)         
results_gen_sig <- data.frame()  

# Loop que recorre cada combinación de PCs y folds
for (pc in PCs) {
  for (fold in folds) {
    file_path <- file.path(models_dir,paste0(region, "_BrainGENIE_retrain-", pc, "_nfolds", fold, ".Rdata"))
    if (file.exists(file_path)) {
      perf <- readRDS(file_path)
      significant <- perf[perf$Cor >= 0.1 & perf$fdr < 0.05, ]
      if (!"Rsq" %in% colnames(significant) || nrow(significant) == 0 || all(is.na(significant$Rsq))) {
        cat("Skipping PCs =", pc, ", folds =", fold, " (no significant genes)\n")
        next
      }
      rsq <- significant$Rsq[!is.na(significant$Rsq)]
      results_gen_sig <- rbind(results_gen_sig, data.frame(
        PCs = pc,
        Folds = fold,
        R2_Min = r2_min,
        R2_Q1 = quantile(rsq, 0.25),
        R2_Median = median(rsq),
        R2_Mean = r2_mean,
        R2_Q3 = quantile(rsq, 0.75),
        R2_Max = r2_max,
        R2_Range = r2_range,
        Cor = mean(significant$Cor), #coef de correlación de pearson
        Predictable_Genes = nrow(significant)
      ))
    }
  }
}

if (nrow(results_gen_sig) > 0) {
  r2_summary_filename <- paste0(region, "_R2_info_sig_genes.xlsx")
  write_xlsx(results_gen_sig, file.path(summary_stats_dir, r2_summary_filename))
}

# 7. PCA y VARIANZA
blood.pca <- fit_pca(gene_list = colnames(data))  # PCA con los datos de sangre
gene_variance <- blood.pca$pca$sdev^2             # Calcular la varianza de cada PC

#Paso exploratorio: calculamos la varianza acumulada de los PCs para decidir cuántos usar en el modelo.
explained_var <- gene_variance / sum(gene_variance)  # Normalize to get explained variance

pcs_to_test <- seq(5, 60, by = 5)  #Testear la varianza acumulada para los PCs en pasos de 5 en 5

#Guardar la varianza acumulada
var_df <- data.frame(
  PCs = pcs_to_test,
  ExplainedVariance = sapply(pcs_to_test, function(n) sum(explained_var[1:n]) * 100)
)

# Guardar las varianza explicadas 
explained_var_filename <- paste0(region, "explained_variance.xlsx")
write_xlsx(var_df, file.path(summary_stats_dir, explained_var_filename)) 


# Plot de la varianza aplicada
plot_var_filename <- paste0(region, "explained_var.png")
png(file.path(plot_dir, plot_var_filename))

plot(var_df$PCs, var_df$ExplainedVariance, type = "b", pch = 19,
     xlab = "PCs", ylab = "Varianza Explicada (%)",
     main = paste("Explained Variance-", region))
dev.off()

#8. IMPUTACIÓN
n_comps <- 50  # Número de PCs para la imputación

trained.models <- fit_lr_weights_in_gtex(
  pca_model = blood.pca,
  gene_list = perf$gene,
  tissue = region,
  n_comps = n_comps
)

### 50 PCs and 10 folds
# Training LR models for: 18957 genes (Brain_Amygdala)
# Training LR models for: 19236 genes (Brain_Anterior_cingulate_cortex_BA24)
# Training LR models for: 20524 genes (Brain_Caudate_basal_ganglia)
# Training LR models for: 20540 genes (Brain_Cerebellar_Hemisphere)
# Training LR models for: 21494 genes (Brain_Cerebellum)
# Training LR models for: 20340 genes (Brain_Cortex)
# Training LR models for: 19983 genes (Brain_Frontal_Cortex_BA9)
# Training LR models for: 20189 genes (Brain_Hippocampus)
# Training LR models for: 20839 genes (Brain_Hypothalamus)
# Training LR models for: 20884 genes (Brain_Nucleus_accumbens_basal_ganglia)
# Training LR models for: 19330 genes (Brain_Putamen_basal_ganglia)
# Training LR models for: 18882 genes (Brain_Substantia_nigra)
#
fit.pca.to.new.samples <- predict_pca(dat = data, pca_model = blood.pca)  # Project PCA

imputed <- impute_gxp(
  pca_in_new_sample = fit.pca.to.new.samples,
  trained_model = trained.models,
  scale = TRUE
)

# ---- 10. GUARDAR LA EXPRESIÓN IMPUTADA ----
output_filename <- paste0(region, "_BrainGENIE_imputed_expression_", n_comps, "PCs.txt")
output_path <- file.path(imputed_dir, output_filename)
write.table(imputed, file = output_path, sep = "\t", quote = FALSE, row.names = TRUE)
cat("La expresión imputada se ha guardado en:", output_path, "\n")

